---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-api
  template:
    metadata:
      labels:
        app: board-api
    spec:
      containers:
      - name: board-api
        image: docker.io/aak1009/goserver
        ports:
        - containerPort: 8081
          name: app
---
apiVersion: v1
kind: Service
metadata:
  name: board-api
  namespace: dev
spec: 
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: board-api

