# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

resources:
- repo: self


stages:
- stage: deploy
  displayName: Build image
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment: 
     name: test123
     resourceType: VirtualMachine
    strategy:
       runOnce:
          deploy:   
            steps:
              - script: apt-get install nginx
  

# - task: AzureKeyVault@2
#   inputs:
#     azureSubscription: 'devopstest'
#     KeyVaultName: 'testkey154'
#     SecretsFilter: '*'
#     RunAsPreJob: false
