# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

resources:
- repo: self


stages:
# - stage: 'Build'
#   displayName: 'Build the application'
#   jobs:
#   - job: 'Build'
#     displayName: 'Build job'
#     pool:
#       vmImages: 'ubuntu-20.04'

- stage: 'DEV'
  displayName: 'Deploy to the dev environment'
  # dependsOn: Build
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment: 
     name: test123
     resourceType: VirtualMachine
    strategy:
       runOnce:
          deploy:   
            steps:
              - script: mkdir ~/.ssh/test
  

# - task: AzureKeyVault@2
#   inputs:
#     azureSubscription: 'devopstest'
#     KeyVaultName: 'testkey154'
#     SecretsFilter: '*'
#     RunAsPreJob: false
