---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  namespace: default
  labels:
    app: board
spec:
  replicas: 1
  selector:
    matchLabels:
       app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
      - name: goserver
        imagePullPolicy: Always
        image: docker.io/aak1009/goserver
        ports:
        - containerPort: 8081
          protocol: TCP
      - name: react-board
        image: docker.io/aak1009/react-board
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: testservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: board