
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdev
  namespace: default
  labels:
    app: testdev
spec:
  replicas: 1
  selector:
    matchLabels:
       app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
      - name: board-api
        image: docker.io/aak1009/goserver
        ports:
        - containerPort: 8081
          name: app
      - name: board-app
        image: docker.io/aak1009/react-board
        ports:
        - containerPort: 80
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: board-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: testdev